apiVersion: v1
kind: Service
metadata:
  name: imps-velocity-system
  labels:
    app.kubernetes.io/name: imps-velocity-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: imps-velocity-system
  ports:
    - name: http
      port: 80
      targetPort: http
